M48
; DRILL file {KiCad (6.0.4)} date Thu Apr  7 14:28:44 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-07T14:28:44+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X84.6Y-49.73
X84.6Y-112.685
X135.94Y-49.73
X135.94Y-112.685
T0
M30
