M48
; DRILL file {KiCad (6.0.4)} date Thu Apr  7 13:27:01 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-07T13:27:01+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.700
%
G90
G05
T1
X43.097Y-48.685
X43.097Y-72.727
X67.139Y-48.685
X67.139Y-72.727
T0
M30
